### ISSUE TITLE
autocomplete services for issues

### ISSUE THREAD

**Issue by cehsu** [sfbrigade/sfsbook#102]
UPDATED on 8/17: 211 implements an autocomplete that provides services for specific issues. 
Synonyms are also a consideration.
<img width="1066" alt="screen shot 2017-08-17 at 9 33 01 pm" src="https://user-images.githubusercontent.com/16051172/29444352-c86de46c-8393-11e7-9105-668f28665ada.png">

**Comment by MosesSupposes** [comment]
I know how to implement this in vanilla JavaScript. Can I give it a try?

**Comment by techieshark** [comment]
@MosesSupposes Maybe outline in a comment the algorithm / process you're thinking about? I'm curious what you have in mind!

**Comment by cehsu** [comment]
Closing per new architecture.
