### ISSUE TITLE
Volunteer info-center page/section

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#11]
This is a New Feature Issue, it's probably too big to be tackled in one go. Please hang (create new issues and link them in the comments here) any smaller related issues on this one so we can keep track of all the work to bring this new feature to life.

Feature description: A section of the guide accessible only to volunteers that gives them the information they usually have to collect at the beginning of a volunteer shift.

**Comment by tsmuse** [comment]
This feature needs more design definition before it can be worked.

**Comment by jaydashuav** [comment]
Volunteer Only Section
	-Hotline Checklist
	-Medical Advocacy Checklist
	-Include your Back Up Staff 
	-Ability for volunteers to communicate?
	-Counselor Support Meetings?
	-Hotline Call updates
	-Easy Access to stat sheets?

**Comment by jaydashuav** [comment]
Also, if we have this section, depending on what we include, we may need notifications when things are updated.
