### ISSUE TITLE
Refactor templating.go into two files

### ISSUE THREAD

**Issue by cehsu** [sfbrigade/sfsbook#110]

**Comment by techieshark** [comment]
@JPZ13 is on it!

**Comment by rjkroege** [comment]
I have a number of complaints in `TODO` but it's not clear to me why / how dividing this file is going to resolve them.  Is there another issue?

**Comment by rjkroege** [comment]
Per slack discussion:

>  if memory serves, the reason you recommended breaking this into two
>  files was because there is some logic that pertains to index.html, and
>  some that is shared across views (namely `parseAndExecuteTemplate`, and
>  therefore `getTemplateStrings`), and that this distinction should be
>  made clearer. Thanks for additional thoughts:)

`templatedServer` implements both `index.html` and `search.html` with (effectively) no difference. I presume that the general idea is to create additional files for the index and search usages that re-use `templatedServer`.  Presumably this would permit simplifying (slightly) the code by factoring out the differences.

**Comment by cehsu** [comment]
Closed per new architecture.
