### ISSUE TITLE
search fails

### ISSUE THREAD

**Issue by techieshark** [sfbrigade/sfsbook#114]
I'm running the latest code from `master` branch, and if I search for something like 'bed' or 'housing' I get this error:

> This site can’t be reached

> The webpage at https://localhost:10443/search.html?search-submit-button=Submit&query=bed might be temporarily down or it may have moved permanently to a new web address.
ERR_SPDY_PROTOCOL_ERROR

Interestingly, if I search for something that returns no results, it works (here, for 'bec' instead of 'bed):

<img width="401" alt="Search result for bec showing no results" src="https://cloud.githubusercontent.com/assets/1072292/23778383/b140439e-04ee-11e7-8546-04283c4f1b96.png">

Here's the error reported on the server backend:

```
2017/03/09 17:32:30 anonymous access
2017/03/09 17:32:30 req.Form map[search-submit-button:[Submit] query:[bed]]
2017/03/09 17:32:30 querystring: bed
2017/03/09 17:32:30 6 matches, showing 1 through 6, took 487.157µs
    1. 0b09c42d-c6ee-4349-890e-7f0b7fdd511f (0.769281)
	name
		A Woman’s Place 3
    2. 8506a1b2-338d-42f4-b226-676f9fd66ba7 (0.747606)
	name
		Episcopal Community Service
    3. 9ce30cb0-6b15-4f55-8444-6d03b9759644 (0.564242)
	name
		Guerrero House
    4. 5370b07a-b923-4956-8f6a-89534660fd11 (0.537675)
	name
		A Safe Place 2
    5. d8f3b91c-9108-444d-8365-e59639abc9ce (0.534611)
	name
		Project Sanctuary, Inc: Mendocino
    6. 26f22ecb-981e-42ad-abaa-f078fe339493 (0.487109)
	name
		SAVE: Shelter Against Violent Environments

2017/03/09 17:32:30 http2: panic serving [::1]:49920: interface conversion: interface {} is nil, not string
goroutine 301 [running]:
net/http.(*http2serverConn).runHandler.func1(0xc4204762e8, 0xc42049bfaf, 0xc4204a4e00)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/h2_bundle.go:4592 +0x190
panic(0x14b3a80, 0xc42028c640)
	/usr/local/Cellar/go/1.8/libexec/src/runtime/panic.go:489 +0x2cf
github.com/sfbrigade/sfsbook/dba.(*QueryResultsGenerator).ForRequest(0xc420156880, 0x152ba20, 0xc420260100, 0xf8, 0xc420260100)
	/Users/peter/go/src/github.com/sfbrigade/sfsbook/dba/query_generator.go:124 +0xf7e
github.com/sfbrigade/sfsbook/server.(*templatedServer).ServeHTTP(0xc420154700, 0x1776360, 0xc4204762e8, 0xc420260100)
	/Users/peter/go/src/github.com/sfbrigade/sfsbook/server/templating.go:38 +0x19e
github.com/sfbrigade/sfsbook/server.(*cookieHandler).ServeHTTP(0xc420150c60, 0x1776360, 0xc4204762e8, 0xc4203fc300)
	/Users/peter/go/src/github.com/sfbrigade/sfsbook/server/user_state.go:169 +0x234
net/http.(*ServeMux).ServeHTTP(0xc420150b70, 0x1776360, 0xc4204762e8, 0xc4203fc300)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2238 +0x130
net/http.serverHandler.ServeHTTP(0xc420090b00, 0x1776360, 0xc4204762e8, 0xc4203fc300)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:2568 +0x92
net/http.initNPNRequest.ServeHTTP(0xc4203f2380, 0xc420090b00, 0x1776360, 0xc4204762e8, 0xc4203fc300)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/server.go:3088 +0x93
net/http.(*initNPNRequest).ServeHTTP(0xc4203d89d0, 0x1776360, 0xc4204762e8, 0xc4203fc300)
	<autogenerated>:312 +0x74
net/http.(Handler).ServeHTTP-fm(0x1776360, 0xc4204762e8, 0xc4203fc300)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/h2_bundle.go:4319 +0x4d
net/http.(*http2serverConn).runHandler(0xc4204a4e00, 0xc4204762e8, 0xc4203fc300, 0xc4200b7aa0)
	/usr/local/Cellar/go/1.8/libexec/src/net/http/h2_bundle.go:4599 +0x89
created by net/http.(*http2serverConn).processHeaders
	/usr/local/Cellar/go/1.8/libexec/src/net/http/h2_bundle.go:4331 +0x4ac
```

This is what the server backend says when searching for 'bec' with no results:
```
2017/03/09 17:36:25 anonymous access
2017/03/09 17:36:25 req.Form map[search-submit-button:[Submit] query:[bec]]
2017/03/09 17:36:25 querystring: bec
2017/03/09 17:36:25 No matches
2017/03/09 17:36:25 this is the template /search.html
2017/03/09 17:36:25 this is the template /head.html
2017/03/09 17:36:25 this is the template /header.html
2017/03/09 17:36:25 this is the template /searchbar.html
2017/03/09 17:36:25 this is the template /footer.html
2017/03/09 17:36:25 anonymous access
2017/03/09 17:36:25 user cookie { 0 0001-01-01 00:00:00 +0000 UTC }
2017/03/09 17:36:25 anonymous access
2017/03/09 17:36:25 user cookie { 0 0001-01-01 00:00:00 +0000 UTC }
2017/03/09 17:36:25 anonymous access
2017/03/09 17:36:25 user cookie { 0 0001-01-01 00:00:00 +0000 UTC }
2017/03/09 17:36:25 anonymous access
2017/03/09 17:36:25 this is the template /favicon.ico
```

**Comment by techieshark** [comment]
@cehsu can you look at your `dba/query_generator.go` file around line 124?

I find I can stop the failure by commenting out some lines:
```
		// results.Resources[c].Services = sr.Fields["services"].(string)
		// results.Resources[c].Categories = sr.Fields["categories"].(string)
		// results.Resources[c].Description = sr.Fields["description"].(string)
		// results.Resources[c].Address = sr.Fields["address"].(string)
		// results.Resources[c].Website = sr.Fields["website"].(string)
		// results.Resources[c].Email = sr.Fields["email"].(string)
```

Then when I search for bed I get this:

![image](https://cloud.githubusercontent.com/assets/1072292/23778812/6211fc9c-04f1-11e7-95a8-0cdd35ba80cf.png)

And clicking on the first result I see this:

![image](https://cloud.githubusercontent.com/assets/1072292/23778798/4fef69be-04f1-11e7-9f3a-9d0f82f7da88.png)

So it seems like what's happening is the server is trying to parse some fields as strings, but they don't exist in the data, hence the error

```
2017/03/09 17:54:55 map[name:A Woman’s Place 3]
2017/03/09 17:54:55 http2: panic serving [::1]:50280: interface conversion: interface {} is nil, not string
```

**Comment by cehsu** [comment]
thanks so much @techieshark I will investigate, and also could you please check whether search works when you: 
1. git clone a fresh copy of the repo, 
2. immediately checkout commit 118a6650461c8432ff018cd044c6428a87512bd7, 
3. run go get, go build, ./sfsbook -init_passwords? 
it would be good to know whether the bug originated after that point or before.

**Comment by techieshark** [comment]
@cehsu yeah that seems to work (results returned, but very different style):

![multiple search results returned for 'bed'](https://cloud.githubusercontent.com/assets/1072292/23779495/a4f61e22-04f5-11e7-9a6c-dc560dabe073.png)

**Comment by techieshark** [comment]
It seems the format of the source data was changed - perhaps unintentionally? - during a recent commit that meant to clean the data.

If you run 

```
cd ~/go/src/github.com/sfbrigade/
git clone https://github.com/sfbrigade/sfsbook.git
cd sfsbook
go get; go build; ./sfsbook -init_passwords
```

You'll see that search fails (try 'bed'), but if you do the same but before `go get`, run:

```
git revert 0cb6c72f98aedec368331899c61a9f97d1a1c200
```

it should work.

If you look at [this commit](https://github.com/sfbrigade/sfsbook/commit/0cb6c72f98aedec368331899c61a9f97d1a1c200) (it's a big one) you'll notice the format of the data changed.

For example, 'email' field becomes 'E-mail':
![image](https://cloud.githubusercontent.com/assets/1072292/23787864/e52e5c6a-0528-11e7-9a84-41bd632b9380.png)

Perhaps the data's structure was supposed to change, and there is some other code that needs to reflect that?

**Comment by cehsu** [comment]
While we investigate the cause, this gets things set up and working:
1. git clone https://github.com/sfbrigade/sfsbook.git  (while within sfbrigade directory)
2. cd sfsbook (to go into the sfsbook directory)
3. git checkout 118a6650461c8432ff018cd044c6428a87512bd7

[12:50]  
4. go get
5. go build
6. ./sfsbook -init_passwords
7. git checkout master
8. go build
9. ./sfsbook

**Comment by cehsu** [comment]
rekey cleaned data to retain original structure.
