### ISSUE TITLE
Make resource data available via an Open API

### ISSUE THREAD

**Issue by cehsu** [sfbrigade/sfsbook#116]
e.g. http://socialservicedata.org/api/

**Comment by greggish** [comment]
Glad to see such progress on this project. 

Through @openreferral, we're promoting the adoption of standardized schema and APIs that can be implemented across technologies and institutional contexts. The [Ohana API](https://github.com/codeforamerica/ohana-api) (developed by Code for America) is a prominent FOSS option, though other organizations have developed their own compatible APIs referencing our schema. 

We just recently announced [a partnership with the Alliance of Information and Referral Systems, funded by Stanford and led by @kinlane, to develop an OpenAPI spec](https://openreferral.org/the-open-referral-api-project/) that would make it easier to design, implement, and update interoperable resource data APIs. I'd be happy to discuss this in greater detail, as you might wish to participate in this process.
