### ISSUE TITLE
User ID system

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#12]
This is a New Feature Issue, it's probably too big to be tackled in one go. Please hang (create new issues and link them in the comments here) any smaller related issues on this one so we can keep track of all the work to bring this new feature to life.

Feature description: We need a user identity system that supports at least two types of users and allows signed in users: write access to the pages of the guide, access to view comments on entries, access to user profile management settings (e.g. password, username, email)

**Comment by tsmuse** [comment]
This system MUST allow three types of users with distinct permissions: unlogged-in users, Volunteer users, and Admin users

**Comment by pamelaalicia** [comment]
**Unlogged-in users**
- Do not require a password to log into the system
- Cannot comment or edit information or tag
- Can view the database, search in the database, etc.
- Cannot see comments

**Volunteer users**
- Require a password to log into the system
- Users are invited to create this account type via security code / admin invitation
- Can comment and see other comments
- Can edit information
- Can view the database, search in the database, etc.
- Can access user profile management settings
- Can view and contribute volunteer section
- Can flag inappropriate comments 

**Admin users**
- Require a password to log into the system
- Users are invited to create this account type via admin invitation
- Can comment and see other comments
- Can edit information
- Can add tags
- Can manage other users' permissions (block users, delete comments, etc.)
- Can view the database, search in the database, etc.
- Can access user profile management settings
- Can view and contribute volunteer section
- Can receive warnings from "flagged" / "reported" inappropriate comments

**User Profile Management*
- When hovering over the username of a volunteer or admin, could we show the affiliated volunteer organization?
- What is required when signing up for an account? Name, email address, volunteer organization, birth date
- What is optional when signing up for an account? Profile picture, can link to FB/Linkedin (?)

**Comment by rjkroege** [comment]
Sub bugs:
*  Account database #47
*  plumb user context #48 
*  cookie handling #49 
*  basic account management interface #50
*  initial password setup #51
*  login screen #52

**Comment by rjkroege** [comment]
The current set of capabilities is adequate to make progress here.
