### ISSUE TITLE
TLS Handshake error when typing url into address bar

### ISSUE THREAD

**Issue by sutapadey** [sfbrigade/sfsbook#129]
Resolved by clicking on link from Github readme. 

2017/03/29 19:25:19 http: TLS handshake error from [::1]:49354: tls: first record does not look like a TLS handshake
2017/03/29 19:25:19 http: TLS handshake error from [::1]:49355: tls: first record does not look like a TLS handshake
2017/03/29 19:25:19 http: TLS handshake error from [::1]:49356: tls: first record does not look like a TLS handshake
2017/03/29 19:26:09 http: TLS handshake error from [::1]:49409: EOF

**Comment by techieshark** [comment]
Thanks for reporting that. I'm not sure exactly how to reproduce though, could you elaborate on what you did and what you saw?

Thanks!

**Comment by techieshark** [comment]
@mwillcox maybe you can add notes on what you did/saw as well.

**Comment by mwillcox** [comment]
@techieshark I'm unable to replicate it now, but maybe next time we onboard/set someone up we can try and debug it more. Only seems to happen on very first setup.

**Comment by techieshark** [comment]
@mwillcox ok thanks. Perhaps we'll get a chance at that tonight.

**Comment by cehsu** [comment]
I'm not getting this error on fresh builds, neither are new members.. closing for now, will reopen if pops up again.
