### ISSUE TITLE
Onboarding system

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#13]
This is a New Feature Issue, it's probably too big to be tackled in one go. Please hang (create new issues and link them in the comments here) any smaller related issues on this one so we can keep track of all the work to bring this new feature to life.

Feature description: We need a self-serv way to onboard new users into the system

**Comment by pamelaalicia** [comment]
**Primary Onboarding
**

My recommendation is to have a multi-stepped contextual FTUE (see below as example)

![image](https://cloud.githubusercontent.com/assets/17677576/14974809/713a3c26-10ae-11e6-9690-188b90d057db.png)

**On Demand Onboarding**
I recommend adding a Help sign in the corner (?) for more information on the current page
When you click on the (?) button helpful tips pop up that guide users as to what they can dp
Ex. On this page you can leave comments regarding X, Y, Z or update information

**Comment by tsmuse** [comment]
That kind of tutorial, a set of overlays, doesn't usually work very well. People tend to skip over them (unless you don't provide a way to skip, then they page through them angrily as quickly as they can). The biggest piece of our onboarding is going to be account creation, there just aren't a lot of features that need to be explained. I'll post the overall site map I've put together as soon as I finish digitizing them. I would suggest focusing on what kind of information we absolutely need to collect (and what would be nice to collect but isn't required) to get someone an account and into the system.
