### ISSUE TITLE
Languages aren't being included

### ISSUE THREAD

**Issue by techieshark** [sfbrigade/sfsbook#134]
When I run the server and visit the site, I search for a resource which is known to support another language, but nothing is shown in the language field on the result page.

To reproduce:
1. Run the server & visit the site
2. Search for "A Safe Place"
3. Look at language field and note it is empty:
![image](https://cloud.githubusercontent.com/assets/1072292/24779435/48d0d334-1ae5-11e7-844b-01fe63ee0915.png)

To confirm that Spanish should be shown, see the `languages` key in the refguide.json under the entry for A Safe Place:
```
  {
    "name": "A Safe Place",
     ...
    "languages": "Spanish",
```

**Comment by techieshark** [comment]
I wonder if it is caused by typo in resource.html template ("languges" missing the 2nd "a")

```
<div class="onefield">
          <label for="languges">Languages</label>
          <input id="languges" type="text" name="languges" size="80" value="{{.Document.languges}}"./>
</div>
```

**Comment by sutapadey** [comment]
You are right, it is caused by a typo on "languges" at line 108 in resource.html

<tr>
            <th>Languages</th>
            <td>{{.Document.languges}}</td>
          </tr>

**Comment by techieshark** [comment]
@sutapadey thanks for reviewing that. I just added a PR that should fix it.
