### ISSUE TITLE
Create job to generate doc based on data in Sheets using a template (autocrat)

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#15]
This is a New Feature Issue, it's probably too big to be tackled in one go. Please hang (create new issues and link them in the comments here) any smaller related issues on this one so we can keep track of all the work to bring this new feature to life.

Feature description: In addition to the screen-front-end styles that we will need for the UI, we need a Media specific style sheet for printers, so that pages of the site (or the whole site itself) can be printed by those who do not have reliable access to the internet.

**Comment by cehsu** [comment]
Since we're moving to Sheets DB stack, would be good to look into autocrat for generating a document based on a template.

**Comment by cehsu** [comment]
- [ ] Document/test out job creation process
- [ ] Document/test out template creation process
