### ISSUE TITLE
Sheets as DB

### ISSUE THREAD

**Issue by cehsu** [sfbrigade/sfsbook#163]
Ensures that data is always available even if the app is not:)

Relevant articles/threads:
[Google Sheets as a Database – INSERT with Apps Script using POST/GET methods (with ajax example)](https://mashe.hawksey.info/2014/07/google-sheets-as-a-database-insert-with-apps-script-using-postget-methods-with-ajax-example/)
[Let Google Chew the CUD](https://medium.com/@silentrant/let-google-chew-the-cud-6ba00584b3d5)
[CRUD interface for Google Sheets?](https://www.reddit.com/r/javascript/comments/4il8y6/crud_interface_for_google_sheets/)

[Relevant projects](https://github.com/search?p=1&q=google+spreadsheet+api&ref=searchresults&type=Repositories&utf8=%E2%9C%93
)

Are there alternatives worth considering? [Airtable](https://airtable.com/api)? [sheetsu](https://sheetsu.com/)? How do they integrate with organizational considerations and project constraints?

**Comment by pravingkumar** [comment]
Need CRUD with webapp with 4 dependent dropdowns for first group selection and 4 4 dependent dropdowns for second group selection. will it be possible for on screen option to change same date for day wise, month wise and year wise.
