### ISSUE TITLE
Search by location

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#17]
This is a New Feature Issue, it's probably too big to be tackled in one go. Please hang (create new issues and link them in the comments here) any smaller related issues on this one so we can keep track of all the work to bring this new feature to life.

Feature description: In addition to the other search features, we need a the ability for users to do a "find near me" style search.

**Comment by pamelaalicia** [comment]
- This should be a tool that works alongside the keyword search but can also be left blank if user does not need to search by location. 
- Do we want to add a map which highlights all the resources in the reference guide based on their address (which would be automatically updated based on logged in user edits) -- similar to how you can create a Google Map with personal saved locations (Google Places)?
- Do we need to tap into something like Google Maps API? (see: https://developers.google.com/maps/documentation/geocoding/intro)
- We need to allow pop-up request permission from the user for access to their location.
- Once permission is acquired, recommend nearby options (similar to Yelp searches) OR if visually feasible (maybe not for MVP)

**Comment by tsmuse** [comment]
blocked by issue #9

**Comment by rjkroege** [comment]
I wish to punt on mapping as part of MVP. Please.
