### ISSUE TITLE
What verifies a user as a Volunteer?

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#23]
As part of [User ID system](https://github.com/sfbrigade/stop-violence/issues/12): We need to define what criteria allow someone to create an account as a Volunteer user.

**Comment by paosolski** [comment]
Since volunteers are associated with an organization, would it be a stretch to require the volunteer enter org-provided password in the account creation flow?

**Comment by jaydashuav** [comment]
If there is an org-provided password, i imagine that every volunteer would log in with the same exact password because I don't imagine the Volunteer Manager to want to generate multiple new passwords at one time.

**Comment by paosolski** [comment]
Maybe password was the wrong term, I think what I'm trying to describe is more similar to a coupon code, except one provided by the VM to the new volunteer that they have to enter into a field as a form of authentication during their new user sign up process.

**Comment by pamelaalicia** [comment]
Here are a few potential paths forward:

1. Assign a new code to each volunteer as a temp password
ex. "WomensOrg24" for volunteer #24

2. Assign a security code to each volunteer organization that allows volunteers to sign up for as a volunteer user
ex. all volunteers can create an account using security code "StopViolencewithWomensOrg"

3. Volunteer organizations submit a list of emails addresses (of new volunteers) to our system which will "invite" users to create a volunteer user login.

I'm not sure which would be easiest so I will defer to the developer on that. :)

**Comment by rjkroege** [comment]
Do we assume that the organization has its own existing email and accounts infrastructure? Or do volunteers have their own email addresses?

If the later, then Google / Facebook / Twitter OAuth for accounts? That way, users just use their GMail or Facebook etc. username / password combo to sign in.

Poll the volunteers?

**Comment by tsmuse** [comment]
We could use OAuth but we still need a way to keep the random-general public from being able to sign up as a volunteer account. This limit is primarily to keep the rando internet griefers from coming in and causing trouble (this site will be a prime target for the worst elements of the internet because of it's content). I think the idea of a password/coupon code thing is a good idea, but we still have to figure out how we administer the codes. We could randomly generate a code that is hard to spoof, that's possible, but the issue we're dancing around is that we need a person(or people) to verify the volunteers are actually volunteers at SFWAR(or one of the other agencies we partner with as we grow.) Unless there is some other factor that all the volunteers have that random members of the public don't, I don't know that we can avoid having a human do the vetting.

**Comment by rjkroege** [comment]
I had presumed that we would only let volunteers edit the material. Sorry that I failed to say this.

How would SFWAR want to deal with this? They must have a scheme to identify volunteers already?

**Comment by tsmuse** [comment]
So I did some more thinking about this and I think the best way to handle this is to create an invite only system where only existing members (or admins) can invite new members. This means the community gets to share the work of verifying new members, which isn't ideal but it's more ideal than expecting an agency(ies) to do this work or expecting one or a few volunteers to community manage a deployment. 
Thoughts? If there are no objections I'll consider that the direction we're moving in and close this issue.

**Comment by rjkroege** [comment]
Sounds reasonable to me. This will become some interesting code.
