### ISSUE TITLE
Design the initial set of tags for the system

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#26]
As part of [Tagging system to allow users to tag entries with relevant metadata](https://github.com/sfbrigade/stop-violence/issues/8):

We need to decide on the initial set of tags we will use to tag each entry with. This should include the sections each entry currently lives in in the PDF, but could also include other tags that we think are useful.

**Comment by rjkroege** [comment]
We can mine the existing categories for tags. I'll update the bug with a list of categories that can be automatically extracted.
