### ISSUE TITLE
Decide: Open or Closed tagging system?

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#27]
As part of [Tagging system to allow users to tag entries with relevant metadata](https://github.com/sfbrigade/stop-violence/issues/8):

We need to decide if we are going to have an open or closed tag system.

Definitions: 
Open tagging system: users can create new tags on the fly. 
Closed tagging system: users must select from a fixed set of tags that can only me modified by an admin.

**Comment by tsmuse** [comment]
Pros for an Open System: 
* Allows the IA to grow organically with the users and the data stored in the system
* Allows tags to be in the language of our users

Cons for an Open System:
* Allows the IA to grow organically with the users and data stored in the system, which means it will need to be pruned regularly to keep it from growing out of control huge.
* Lots of duplicates end up in most open systems (e.g. pants, trousers, drawrs, jeans)

**Comment by tsmuse** [comment]
Pros for a Closed System:
* Fewer choices for users to make while tagging, increasing the likelihood that they will tag new and existing entries. 
* Easier for us to maintain, no need to monitor the system to deal with duplicates

Cons for a Closed System:
* More work for us upfront to make sure we have a large enough tag set that works
* Can lead to people tagging things incorrectly because they are [satisficing](https://en.wikipedia.org/wiki/Satisficing) on a tag choice.

**Comment by tsmuse** [comment]
I would lean toward a closed system at this point, just for simplicity, but I'd love to hear everyone's thoughts on the choice.

**Comment by covalwill** [comment]
@tsmuse I'm in favor of closed tag system. 
* Easy to maintain
* Set definitions
* Ties entries to their proper or closest definition

**Comment by rjkroege** [comment]
I think that we can probably build the backend and database to support both. That way, we can late bind this decision with the users.

**Comment by rjkroege** [comment]
Also: I like the .tag vs tag scheme found on pinboard where .tag are private to the user adding the .tag while tag(s) are visible across signed in (or all) users. WDYT?

**Comment by tsmuse** [comment]
It sounds like closed is the popular way to go (at least as far as the user-facing parts of the system are concerned.) I also think closed if best for the users and consistency of the data at this point.  Closing this issue as resolved: "Closed tagging system"
