### ISSUE TITLE
Design a page template to display a list of search results

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#29]
As part of [Search](https://github.com/sfbrigade/stop-violence/issues/9):

We need to design a page template to display a list of search results.

This page MUST show a reasonable number of entries
The page MUST allow for pagination
This page MUST be a11y standards compliant

**Comment by tsmuse** [comment]
Initial wireframe (specifying req'd content only): https://github.com/sfbrigade/stop-violence/blob/master/design/search_results_wire.png

**Comment by techieshark** [comment]
Wireframe mentioned previously has been moved

https://github.com/sfbrigade/sfsbook/blob/master/design/Diagrams_and_sketches/search_results_wire.png
