### ISSUE TITLE
Search by Affordability

### ISSUE THREAD

**Issue by pamelaalicia** [sfbrigade/sfsbook#31]
This is a New Feature Issue, it's probably too big to be tackled in one go. Please hang (create new issues and link them in the comments here) any smaller related issues on this one so we can keep track of all the work to bring this new feature to life.

Feature description: We need a search system that allows users to filter for "free" services given some end users may have a low income background. This should work alongside the keyword search feature but can be left blank if not needed by user.

The cost of the service is noted in the resource database (and can be edited by users) and will range from $0 to $infinity. Users can type in any number (no text) in this search filter.

**Comment by tsmuse** [comment]
blocked by issue #9
