### ISSUE TITLE
Define high-level Architecture

### ISSUE THREAD

**Issue by rjkroege** [sfbrigade/sfsbook#32]
Per the title: define the architecture of the system.

**Comment by rjkroege** [comment]
# Obvious
* Webapp. So client (web browser) and backend server.
* Privacy matters so https support required.
* Data size is small (10k lines of JSON represents the entire resource set.) This is maybe a ~1000 entries? Design can hence favour simplicity over scalability.
* There is (amongst other pages) an *entry* page that contains a single entry from the directory.
* Backend serves up static resources, app pages, entries.

# For Discussion
* Each *entry* gets its own URL.
* An entry is available in JSON or HTML from this URL based on URL parameters. This admits a very simple website to start that can be evolved in various ways.
* Edits to a page are done via `XHR` of JSON data. No reloading of the entry should be necessary. (i.e. if the user has to hit reload in the browser to see the correct state, we have failed.)
* JS assets are minified (as needed) when the backend serves them. (i.e. backend is responsible, not the build system.)
* debug URL parameter disables minification

**Comment by tsmuse** [comment]
I like the sound of all of this!

**Comment by rjkroege** [comment]
As for the backend implementation, I'm imagining something like this (in no particular order):

# Stack
*  Go app
*  Default router
*  graceful shutdown control

# Entities
* The *entry* is the core entity
* An entry has a title, some payload fields
* An entry has zero or more *tag*s

# Indexing
MVP: concatenate entire entry, build a text index for it? Add recognizer for additional metadata: phone number, address, hours etc. Huge long tail of stuff.

# Query
Result set is (bounded?) list of entries sorted in descending order by relevance. Set of matchers. Matchers in decreasing relevance order:

*  tag match
*  title (or other identified metadata field) match
*  low-brow stem by regexp expansion?

Bound the number?

# Feature Notes
## Entry URL generation
*  generate URLs by sanitizing entry name with the addition of a short hash.
*  editing a URL creates a redirect name to the previous version.
*  when creating a new entry that collides with an existing entry, the hash is updated.
*  hash: compute checksum of entry title (why: no database or sync needed)
*  modifications to an entry don't alter the url

**Comment by rjkroege** [comment]
Idea: use UUIDs to identify each reference entry as they can be assigned in parallel and are easily computed.

**Comment by greggish** [comment]
FYI, [the Open Referral format](https://github.com/codeforamerica/openreferral) includes [a specification](https://github.com/codeforamerica/OpenReferral/blob/master/Human%20Services%20Data%20Specification%20%20v1.0.md#appendix-a) for structuring UUIDs, as well as a model for structuring phone, hours, and much of the 'long tail of stuff.' 

Of course, it's a whole other challenge to figure out who in the world should be responsible for assigning UUIDs. And our spec doesn't help with that challenge. But we are working with a set of institutions that maintain, and are starting to publish, this data for the SF region. Happy to discuss further, if you're interested.

**Comment by rjkroege** [comment]
Please message me about this on slack. The wip code makes it easy to have an external UUID if we deem this useful. My intent with this comment was to remind myself to create UUIDs for the internal use of the implementation -- more something to join over that could be assigned without a transaction than something for communication outside of the sfsbook app.

**Comment by rjkroege** [comment]
I think the current code largely shows that lay of the architecture modulo a lot of refactoring. I'm claiming this is fixed.
