### ISSUE TITLE
Hosting

### ISSUE THREAD

**Issue by rjkroege** [sfbrigade/sfsbook#33]
Decide on how/where to host the running system.

**Comment by rjkroege** [comment]
I propose GCE.

Pros:
*  I know how already.
*  It's comparatively easy.
*  We might be able to get it for free eventually.

**Comment by tsmuse** [comment]
Sounds good to me. The only alternative I had was to spin up another droplet on DigitalOcean, but we have ~0% chance of them donating it to us, so.... :) @rjkroege Can you set it up and we can discuss who needs to have access to it on Wednesday?

**Comment by rjkroege** [comment]
It would be convenient to have our final name for this.

**Comment by rjkroege** [comment]
We have a name, a DNS entry and I've talked to people here at C4SF to let us get a host using their infrastructure. Updates to follow.
