### ISSUE TITLE
Clean up refguide.csv

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#36]
The JSONified version of the guide data is still not totally ready for prime time. There is a "hand_sort" key in each entry that contains all the data that couldn't be meaningfully scraped out of the PDF. There just wasn't enough context around it to be able to tell what it was. We need to go though and work through the "hand_sort" items to give them meaningful and accurate metadata.

**Comment by tsmuse** [comment]
I left entries that were clearly labels like "Crisis line: Business line: Fax:" in the hand_sort data because I thought it might help clarify what the random phone numbers or numbers or words in the set could be. They can safely be deleted once the other info in the set has a meaningful label.

**Comment by rjkroege** [comment]
It's a whole separate task but... it would be nice to have some automatic support for data cleaning.

**Comment by tsmuse** [comment]
@rjkroege that's a v2 feature, I think :)

**Comment by tsmuse** [comment]
Some guidance on this task to keep us from doing overlapping work:

* Create a branch for this. If you don't know how to do that, send me a message or an email and I'll walk you through it. 
* To keep us from doing duplicate work, you should claim a group of lines in the file here in the comments before you start. There are 379 rows in the file. It's probably easiest to claim them in batches of 50 or less. (e.g. "I'm going to clean up rows 2-35 tonight") 
* post here again when you're completed a batch, that way we'll know when we're all done and we can merge the branches back into master (if you don't know exactly what that last part means don't worry about it yet.)

**Comment by jaydashuav** [comment]
Rows 1-30

**Comment by pamelaalicia** [comment]
Notes:

**Comment by pamelaalicia** [comment]
Remember!
> Cut and paste to the right place
> Unnecessary labels (ex. TDD) should just be deleted just delete
> When you see data in the wrong field (ex. address in email address), move it
> Row is complete when all handsort columns is empty
