### ISSUE TITLE
certificate management

### ISSUE THREAD

**Issue by rjkroege** [sfbrigade/sfsbook#39]
We will need a certificate. But beyond having a certificate, our server has to have the private key.  This information cannot be kept in github. Whoever does deployment builds needs to safeguard the private key and add it to the infrastructure.

Debug builds will manufacture their own certificate if one does not exist at runtime.

**Comment by rjkroege** [comment]
Let me clarify this issue: it's to get an official certificate for sfsbook.

**Comment by rjkroege** [comment]
See #40 for the related server task.

**Comment by tsmuse** [comment]
@rjkroege This is what I was thinking of last night when we talked about this. Rereading it this morning though I'm not sure if it will work for what we're doing. https://letsencrypt.org/
