### ISSUE TITLE
Compile SASS Files

### ISSUE THREAD

**Issue by JonasMS** [sfbrigade/sfsbook#54]

**Comment by mccollek** [comment]
Added process in wiki to use sass in a parallel directory.  If it's decided to go this way, a separate sfsbook-sass would need created.  Either way neither Ruby nor gems need be added to the main repo.

**Comment by rjkroege** [comment]
Why do we need a parallel directory? [`libsass`](http://sass-lang.com/libsass) embedded in the golang server would fit better with the existing (albeit) nascent deployment architecture?
