### ISSUE TITLE
Tagging system to allow users to tag entries with relevant metadata

### ISSUE THREAD

**Issue by tsmuse** [sfbrigade/sfsbook#8]
This is a New Feature Issue, it's probably too big to be tackled in one go. Please hang (create new issues and link them in the comments here) any smaller related issues on this one so we can keep track of all the work to bring this new feature to life.

Feature description: We need the ability to allow signed in users to tag each entry with relevant metadata so entries can be found easier

**Comment by pamelaalicia** [comment]
Potential issue: One problem I foresee with allowing users to tag each entry with free text is that we may end up with a lot of incorrect spelling or phrasing (see examples below). Could we flag incorrect spelling and have suggested auto-completed words based on dictionary spelling / words in the reference guide?

Ex. "partenr", "partner " (partner with a space)

**Comment by tsmuse** [comment]
This is an interesting standard we should consider building on: http://about.auntbertha.com/openeligibility

**Comment by tsmuse** [comment]
I put up an initial list of tags that I think we should launch with. Would love more eyes on them. A lot of them are just the categories from the PDF's TOC, but some of that wording is confusing (at least to me.) I cleaned up things where it made sense (e.g. removed "Legal:" prefix from lawyers and DA/Police) Not sure if there are missing categories still or if we can clean up other things tag names more. 

Tag list: https://github.com/sfbrigade/sfsbook/wiki/Tags-Categories
